import tiktoken

# Get the tokenizer (encoder/decoder) that matches a specific model.
# Different models can use slightly different tokenization rules.
encoder = tiktoken.encoding_for_model("gpt-4o")

# This is the input text we want to convert into tokens.
text = "Hey There! My name is Rumon"

# Convert the text into a list of integer tokens.
# Tokens are not words — they can be whole words, parts of words, or even punctuation.
tokens = encoder.encode(text)

# Example output:
# Tokens: [25216, 3274, 0, 3673, 1308, 382, 52325, 263]
# Each number represents a piece of the original text.
print("Tokens:", tokens)

# ------------------------------------------------------------

# In real LLM usage:
# 1. Your input text is converted into tokens.
# 2. The model processes these tokens.
# 3. The model keeps on generating NEW tokens.
# 4. Those generated tokens are then decoded back into human-readable text.

# Here, we manually decode a list of tokens back into text.
# Normally, you'd decode tokens generated by the model.
decoded = encoder.decode([25216, 3274, 0, 3673, 1308, 382, 52325, 263])

print("=" * 30)

# Convert tokens back into readable text.
print("Decoded:", decoded)
